"""empty message

Revision ID: 08d2b2f13cf7
Revises: 43ccfde0d49e
Create Date: 2022-07-24 23:58:08.425849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d2b2f13cf7'
down_revision = '43ccfde0d49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table_pantry',
    sa.Column('Pantry_id', sa.Integer(), nullable=False),
    sa.Column('Ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['Pantry_id'], ['pantry.id'], ),
    sa.PrimaryKeyConstraint('Pantry_id', 'Ingredient_id')
    )
    op.create_table('association_table_recipe',
    sa.Column('Recipe_id', sa.Integer(), nullable=False),
    sa.Column('Ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['Recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('Recipe_id', 'Ingredient_id')
    )
    op.drop_table('association_table')
    op.add_column('recipe', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('recipe_id_user_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    op.drop_column('recipe', 'id_user')
    op.drop_column('recipe', 'id_ingredient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('id_ingredient', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_id_ingredient_fkey', 'recipe', 'ingredient', ['id_ingredient'], ['id'])
    op.create_foreign_key('recipe_id_user_fkey', 'recipe', 'user', ['id_user'], ['id'])
    op.drop_column('recipe', 'user_id')
    op.create_table('association_table',
    sa.Column('Pantry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ingredient_id'], ['ingredient.id'], name='association_table_Ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['Pantry_id'], ['pantry.id'], name='association_table_Pantry_id_fkey'),
    sa.PrimaryKeyConstraint('Pantry_id', 'Ingredient_id', name='association_table_pkey')
    )
    op.drop_table('association_table_recipe')
    op.drop_table('association_table_pantry')
    # ### end Alembic commands ###
