"""empty message

Revision ID: 262e799de4ed
Revises: ad1bccc456df
Create Date: 2022-08-04 16:39:48.232377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262e799de4ed'
down_revision = 'ad1bccc456df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'allergy',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'allergy',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
