"""empty message

Revision ID: 2d6c8c1f305b
Revises: 95c22ebc8418
Create Date: 2022-08-03 00:17:20.173970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6c8c1f305b'
down_revision = '95c22ebc8418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipe', sa.Column('portion', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'portion')
    op.drop_table('recipe_step')
    op.drop_table('step')
    # ### end Alembic commands ###
