"""empty message

Revision ID: 43ccfde0d49e
Revises: d06fc52b6752
Create Date: 2022-07-24 23:40:33.633647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ccfde0d49e'
down_revision = 'd06fc52b6752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('I_details_pantry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('i_details_portion', sa.Integer(), nullable=False),
    sa.Column('i_details_measure', sa.String(length=50), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('I_details_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('i_details_portion', sa.Integer(), nullable=False),
    sa.Column('i_details_measure', sa.String(length=50), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table',
    sa.Column('Pantry_id', sa.Integer(), nullable=False),
    sa.Column('Ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['Pantry_id'], ['pantry.id'], ),
    sa.PrimaryKeyConstraint('Pantry_id', 'Ingredient_id')
    )
    op.drop_constraint('ingredient_pantry_id_fkey', 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'pantry_id')
    op.drop_column('ingredient', 'ingredient_measure')
    op.drop_column('ingredient', 'ingredient_portion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_portion', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('ingredient', sa.Column('ingredient_measure', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('ingredient', sa.Column('pantry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ingredient_pantry_id_fkey', 'ingredient', 'pantry', ['pantry_id'], ['id'])
    op.drop_table('association_table')
    op.drop_table('I_details_recipe')
    op.drop_table('I_details_pantry')
    # ### end Alembic commands ###
