"""empty message

Revision ID: 57c8cd1126e9
Revises: 
Create Date: 2022-08-04 19:07:42.040651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57c8cd1126e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_id_recipe_fkey', 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'id_recipe')
    op.add_column('recipe', sa.Column('portion', sa.Integer(), nullable=False))
    op.add_column('recipe', sa.Column('time', sa.String(), nullable=False))
    op.add_column('recipe', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('recipe_id_user_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    op.drop_column('recipe', 'date_creation')
    op.drop_column('recipe', 'id_user')
    op.drop_column('recipe', 'steps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('steps', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('date_creation', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_id_user_fkey', 'recipe', 'user', ['id_user'], ['id'])
    op.drop_column('recipe', 'user_id')
    op.drop_column('recipe', 'time')
    op.drop_column('recipe', 'portion')
    op.add_column('ingredient', sa.Column('id_recipe', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ingredient_id_recipe_fkey', 'ingredient', 'recipe', ['id_recipe'], ['id'])
    # ### end Alembic commands ###
