"""empty message

Revision ID: 5a1ff1480e45
Revises: 59a829c0862c
Create Date: 2022-07-29 17:25:54.683609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1ff1480e45'
down_revision = '59a829c0862c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('id_ingredient_1', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_2', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_2'], ['id'])
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'id_ingredient_2')
    op.drop_column('recipe', 'id_ingredient_1')
    # ### end Alembic commands ###
