"""empty message

Revision ID: 7ba7ae2cf49a
Revises: 1064ec86800e
Create Date: 2022-08-03 01:50:45.673088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba7ae2cf49a'
down_revision = '1064ec86800e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('i_details_portion', sa.Integer(), nullable=False),
    sa.Column('i_details_measure', sa.String(length=50), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe_step')
    op.drop_table('I_details_recipe')
    op.add_column('favorite', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.drop_constraint('favorite_id_recipe_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'recipe', ['recipe_id'], ['id'])
    op.drop_column('favorite', 'id_recipe')
    op.add_column('step', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'step', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_column('step', 'recipe_id')
    op.add_column('favorite', sa.Column('id_recipe', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_id_recipe_fkey', 'favorite', 'recipe', ['id_recipe'], ['id'])
    op.drop_column('favorite', 'recipe_id')
    op.create_table('I_details_recipe',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"I_details_recipe_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('i_details_portion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('i_details_measure', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='I_details_recipe_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='I_details_recipe_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='I_details_recipe_pkey')
    )
    op.create_table('recipe_step',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='recipe_step_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], name='recipe_step_step_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_step_pkey')
    )
    op.drop_table('ingredient_recipe')
    # ### end Alembic commands ###
