"""empty message

Revision ID: ac8a8e0038d7
Revises: 5a1ff1480e45
Create Date: 2022-07-29 17:30:07.688635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8a8e0038d7'
down_revision = '5a1ff1480e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('id_ingredient_3', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_4', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_5', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_6', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_7', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_8', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_9', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_1', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_2', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_3', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_4', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_5', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_6', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_7', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_8', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_9', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_1', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_2', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_3', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_4', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_5', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_6', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_7', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_8', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_9', sa.String(length=250), nullable=True))
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_7'], ['id'])
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_3'], ['id'])
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_5'], ['id'])
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_4'], ['id'])
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_9'], ['id'])
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_8'], ['id'])
    op.create_foreign_key(None, 'recipe', 'ingredient', ['id_ingredient_6'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'step_by_step_9')
    op.drop_column('recipe', 'step_by_step_8')
    op.drop_column('recipe', 'step_by_step_7')
    op.drop_column('recipe', 'step_by_step_6')
    op.drop_column('recipe', 'step_by_step_5')
    op.drop_column('recipe', 'step_by_step_4')
    op.drop_column('recipe', 'step_by_step_3')
    op.drop_column('recipe', 'step_by_step_2')
    op.drop_column('recipe', 'step_by_step_1')
    op.drop_column('recipe', 'ingredient_quantity_9')
    op.drop_column('recipe', 'ingredient_quantity_8')
    op.drop_column('recipe', 'ingredient_quantity_7')
    op.drop_column('recipe', 'ingredient_quantity_6')
    op.drop_column('recipe', 'ingredient_quantity_5')
    op.drop_column('recipe', 'ingredient_quantity_4')
    op.drop_column('recipe', 'ingredient_quantity_3')
    op.drop_column('recipe', 'ingredient_quantity_2')
    op.drop_column('recipe', 'ingredient_quantity_1')
    op.drop_column('recipe', 'id_ingredient_9')
    op.drop_column('recipe', 'id_ingredient_8')
    op.drop_column('recipe', 'id_ingredient_7')
    op.drop_column('recipe', 'id_ingredient_6')
    op.drop_column('recipe', 'id_ingredient_5')
    op.drop_column('recipe', 'id_ingredient_4')
    op.drop_column('recipe', 'id_ingredient_3')
    # ### end Alembic commands ###
