"""empty message

Revision ID: acd0dfea1233
Revises: 8d5ab99db160
Create Date: 2022-07-15 15:32:45.852373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd0dfea1233'
down_revision = '8d5ab99db160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('usuario', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('usuario', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('usuario', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('usuario', sa.Column('allergy', sa.String(length=50), nullable=False))
    op.add_column('usuario', sa.Column('user_name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'usuario', ['user_name'])
    op.create_unique_constraint(None, 'usuario', ['email'])
    op.drop_column('usuario', 'mail')
    op.drop_column('usuario', 'nombre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('mail', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'user_name')
    op.drop_column('usuario', 'allergy')
    op.drop_column('usuario', 'country')
    op.drop_column('usuario', 'email')
    op.drop_column('usuario', 'last_name')
    op.drop_column('usuario', 'name')
    # ### end Alembic commands ###
