"""empty message

Revision ID: ad1bccc456df
Revises: ef7399dee394
Create Date: 2022-08-03 08:53:36.424091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1bccc456df'
down_revision = 'ef7399dee394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_unit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'ingredient_unit')
    # ### end Alembic commands ###
