"""empty message

Revision ID: bc0c5f4bf71a
Revises: ac8a8e0038d7
Create Date: 2022-08-02 09:55:39.607858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0c5f4bf71a'
down_revision = 'ac8a8e0038d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'ingredient_portion',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingredient', 'ingredient_measure',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'ingredient_measure',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ingredient', 'ingredient_portion',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
