"""empty message

Revision ID: bc0e12a32cad
Revises: 80d1ee042af3
Create Date: 2022-07-21 02:38:14.472312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0e12a32cad'
down_revision = '80d1ee042af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_measure', sa.String(length=50), nullable=False))
    op.add_column('pantry', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('pantry_id_user_fkey', 'pantry', type_='foreignkey')
    op.create_foreign_key(None, 'pantry', 'user', ['user_id'], ['id'])
    op.drop_column('pantry', 'quantity')
    op.drop_column('pantry', 'id_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantry', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pantry', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pantry', type_='foreignkey')
    op.create_foreign_key('pantry_id_user_fkey', 'pantry', 'user', ['id_user'], ['id'])
    op.drop_column('pantry', 'user_id')
    op.drop_column('ingredient', 'ingredient_measure')
    # ### end Alembic commands ###
