"""empty message

Revision ID: c01037ac4c7c
Revises: 08d2b2f13cf7
Create Date: 2022-07-25 00:00:37.774603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c01037ac4c7c'
down_revision = '08d2b2f13cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'ingredient_quantity')
    op.drop_column('recipe', 'date_creation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('date_creation', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
