"""empty message

Revision ID: d06fc52b6752
Revises: bc0e12a32cad
Create Date: 2022-07-23 01:15:00.182858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06fc52b6752'
down_revision = 'bc0e12a32cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.add_column('ingredient', sa.Column('pantry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredient', 'pantry', ['pantry_id'], ['id'])
    op.drop_constraint('pantry_id_ingredient_fkey', 'pantry', type_='foreignkey')
    op.drop_column('pantry', 'id_ingredient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantry', sa.Column('id_ingredient', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('pantry_id_ingredient_fkey', 'pantry', 'ingredient', ['id_ingredient'], ['id'])
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'pantry_id')
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('allergy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profile_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'name', 'last_name', 'country', 'allergy', 'user_name', name='profile_pkey')
    )
    # ### end Alembic commands ###
