"""empty message

Revision ID: ef7399dee394
Revises: bc0c5f4bf71a
Create Date: 2022-08-02 18:07:17.838046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7399dee394'
down_revision = 'bc0c5f4bf71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('id_recipe', sa.Integer(), nullable=False))
    op.add_column('ingredient', sa.Column('ingredient_weight', sa.Integer(), nullable=True))
    op.add_column('ingredient', sa.Column('ingredient_volume', sa.String(length=50), nullable=True))
    op.add_column('ingredient', sa.Column('ingredient_quantity', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'ingredient', 'recipe', ['id_recipe'], ['id'])
    op.drop_column('ingredient', 'ingredient_portion')
    op.drop_column('ingredient', 'ingredient_measure')
    op.add_column('recipe', sa.Column('steps', sa.String(length=250), nullable=False))
    op.drop_constraint('recipe_id_ingredient_9_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_7_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_3_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_1_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_4_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_2_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_6_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_5_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_id_ingredient_8_fkey', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'id_ingredient_2')
    op.drop_column('recipe', 'step_by_step_2')
    op.drop_column('recipe', 'step_by_step_5')
    op.drop_column('recipe', 'id_ingredient_6')
    op.drop_column('recipe', 'ingredient_quantity_9')
    op.drop_column('recipe', 'step_by_step_9')
    op.drop_column('recipe', 'id_ingredient_5')
    op.drop_column('recipe', 'step_by_step_3')
    op.drop_column('recipe', 'ingredient_quantity_3')
    op.drop_column('recipe', 'id_ingredient')
    op.drop_column('recipe', 'ingredient_quantity_6')
    op.drop_column('recipe', 'step_by_step_1')
    op.drop_column('recipe', 'step_by_step')
    op.drop_column('recipe', 'ingredient_quantity')
    op.drop_column('recipe', 'ingredient_quantity_7')
    op.drop_column('recipe', 'id_ingredient_1')
    op.drop_column('recipe', 'id_ingredient_9')
    op.drop_column('recipe', 'step_by_step_8')
    op.drop_column('recipe', 'ingredient_quantity_8')
    op.drop_column('recipe', 'step_by_step_7')
    op.drop_column('recipe', 'ingredient_quantity_1')
    op.drop_column('recipe', 'ingredient_quantity_2')
    op.drop_column('recipe', 'ingredient_quantity_4')
    op.drop_column('recipe', 'id_ingredient_4')
    op.drop_column('recipe', 'step_by_step_6')
    op.drop_column('recipe', 'step_by_step_4')
    op.drop_column('recipe', 'image_recipe')
    op.drop_column('recipe', 'id_ingredient_7')
    op.drop_column('recipe', 'ingredient_quantity_5')
    op.drop_column('recipe', 'id_ingredient_8')
    op.drop_column('recipe', 'id_ingredient_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('id_ingredient_3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_8', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('image_recipe', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_4', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_6', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_7', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_8', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_8', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_9', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('step_by_step', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('step_by_step_1', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recipe', sa.Column('ingredient_quantity_3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_3', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_9', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('ingredient_quantity_9', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_5', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('step_by_step_2', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('id_ingredient_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_id_ingredient_8_fkey', 'recipe', 'ingredient', ['id_ingredient_8'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_5_fkey', 'recipe', 'ingredient', ['id_ingredient_5'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_fkey', 'recipe', 'ingredient', ['id_ingredient'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_6_fkey', 'recipe', 'ingredient', ['id_ingredient_6'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_2_fkey', 'recipe', 'ingredient', ['id_ingredient_2'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_4_fkey', 'recipe', 'ingredient', ['id_ingredient_4'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_1_fkey', 'recipe', 'ingredient', ['id_ingredient_1'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_3_fkey', 'recipe', 'ingredient', ['id_ingredient_3'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_7_fkey', 'recipe', 'ingredient', ['id_ingredient_7'], ['id'])
    op.create_foreign_key('recipe_id_ingredient_9_fkey', 'recipe', 'ingredient', ['id_ingredient_9'], ['id'])
    op.drop_column('recipe', 'steps')
    op.add_column('ingredient', sa.Column('ingredient_measure', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ingredient', sa.Column('ingredient_portion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'ingredient_quantity')
    op.drop_column('ingredient', 'ingredient_volume')
    op.drop_column('ingredient', 'ingredient_weight')
    op.drop_column('ingredient', 'id_recipe')
    # ### end Alembic commands ###
